### ISSUE TITLE
A compilation error using gfortran 11.2.0

### ISSUE THREAD

**Issue by Liuyaguangzz** [JanThorbecke/OpenSource#10]
Dear sir,
I tried to install your code on Ubuntu 22.04. The default version of gcc and gfortran is 11.2.0. And I get this error message when make the MDD:
```
gfortran ......
/usr/bin/ld: deconvolve.o:(.bss+0x0): multiple definition of `cB'; mdd.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
```
I noticed when I used gfortran 4.8.5 to complie it, everything is fine. So maybe the new version of gfortran has stricter syntax. 

Then I check the code and find there are two same variable definitions in MDD/deconvolve.c and MDD/mdd.c

<img width="950" alt="微信截图_20220620182051" src="https://user-images.githubusercontent.com/46919572/174581534-c7c5fc54-06d7-4505-a8ed-7d3a2c3b44a6.png">

<img width="956" alt="微信截图_20220620182059" src="https://user-images.githubusercontent.com/46919572/174581555-a837b6ef-e850-452c-a730-cd19da5618e5.png">

I change the variable name in deconvolve.c to solve the problem. 
I want to know if this change will affect the operation of the program. If it doesn't, I suggest you to fix this bug.

**Comment by JanThorbecke** [comment]
Thank you for reporting this bug and proposing a fix. At the moment I’m at a conference and I’m not sure if the fix will not change the working of the program. Next week I’m back and will investigate this further. 

Note that the use of this variable only effects the mdd program when the option mdd=3(lsqr) is used. The other options of mdd will work fine, all other programs are also not affected.

Thanks again for reporting this !

With kind regards,

Jan
