### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by rifasuhaz** [JanThorbecke/OpenSource#11]
I am trying to install OpenSource on my Mac M1. But I'm facing an issue where some gfortran symbols are said to be undefined. I have installed gfortran and it seems to be working fine. 
[error.txt](https://github.com/JanThorbecke/OpenSource/files/11823761/error.txt)
<img width="1201" alt="error" src="https://github.com/JanThorbecke/OpenSource/assets/89914286/d81fe1d0-4f5f-402c-a372-79ccf448f72e">

**Comment by JanThorbecke** [comment]
Dear Rifasuhaz,

This could be caused by an incompatibility between gfortran-12 and clang installed on ARM based macs. To overcome the problem you can comment out the ‘OUCH’ function in optRemez.f starting at line 456 until line 466. Then recompile the library and the linking in main should then pass without errors. 

with kind regards,

Jan

**Comment by rifasuhaz** [comment]
Thanks. That solved the issue. But now I am facing another error as attached.

<img width="1440" alt="error" src="https://github.com/JanThorbecke/OpenSource/assets/89914286/ebed212d-c07a-428c-b054-ec1d2e888aad">

**Comment by JanThorbecke** [comment]
Dear Rifasuhaz, 

On my Apple M1, using clang (14.0.3) from the installed Xcode, I only get a warning about these argument mismatches. The clang you use from home-brew (16.0.6) is more strict : see https://github.com/FreeRDP/FreeRDP/issues/8487

Attached is a deconvolve.c that avoids these mismatches. I have not yet committed this change because I wanted to test if the code still works fine. I do not expect that it will fail but prefer to test all changes that are made before committing. 

with kind regards, 

Jan

**Comment by rifasuhaz** [comment]
Thanks a lot. I have installed it successfully. I had a query regarding fdelmodc. Is it implemented with staggering in time? Referring to [Jean Virieux](https://library.seg.org/doi/10.1190/1.1442147#), the grid is staggered in time. 

With regards,
Rifa

**Comment by JanThorbecke** [comment]
Yes the code is staggered in time as well.

Jan

**Comment by rifasuhaz** [comment]
Could you tell me which part of the fdelmodc code deals with this time stagger? I do understand that the stress updates happen after the particle-velocity updates, as mentioned in the fdelmodcManual. I went through the code files, but I couldn't find it. How is it made sure that the updates indeed happen with a time stagger?

Thanks, 
Rifa

**Comment by JanThorbecke** [comment]
Dear Rifa, 

The fact that the stress updates happen after the particle-velocity updates makes it staggered in time. The particle velocity update use P-dt/2 (from the previous time step) and the pressure update uses the pressure at the already update time Vz+dt/2 .

with kind regards, 

Jan

**Comment by rifasuhaz** [comment]
Okay, if so, we are calculating V(t) from P(t-dt/2) and P(t) from V(t), but this implies that P and V exist at t, which should not be the case? But it could be correct if it is P(t+dt/2) that is computed from V(t). What ensures this?

<img width="644" alt="Vx" src="https://github.com/JanThorbecke/OpenSource/assets/89914286/8f3f6b99-ef6c-4dc5-bce2-f3d2232b9f9d">
<img width="667" alt="Px" src="https://github.com/JanThorbecke/OpenSource/assets/89914286/4c5f48bd-f4be-4d76-b7b0-698bed39df8b">

In the above-attached snippets from elastic4.c, I need help understanding the time variable that denotes this change. In the fdelmodc.c file, the main loop over the number of time steps is common for both V and P that is computed? It'd be great if you could let me know this.

Thanks a lot for the previous responses
With regards,
Rifa

**Comment by JanThorbecke** [comment]
Hello Rifa, 

Did you had a look at the manual, equation 3 and the text at the bottom of page 6 tries to explain the staggered time implementation. 

The source code first updates Vx and Vz with for example for Vx

Vx(t+dt/2) = Vx(t-dt/2) + d/dx(P(t-dt))

then P is updated 

P (t) = P(t-dt) + d/dx(Vx(t+dt/2)) + d/dz(Vz (t+dt/2)

This keep P at time t+i*dt and Vx/Vz at time t+i*dt/2. This is the scheme of Virieux in equation 5 of his 1986 paper. 

That the time at time-step are staggered is time can also be explained b y considering that at time step i Vx and Vz are updates form P at time of the PREVIOUS step. After that P is updated with Vx and Vz at the CURRENT step and the updated V and P  are not at the same time grid. 

Does this explanation help you to understand the implementation?

with kind regards, 

Jan

**Comment by rifasuhaz** [comment]
Yes, I get the hang of it now. Thanks a lot:)

Rifa

**Comment by rifasuhaz** [comment]
Dear JanThorbecke,

I had another query regarding fdelmodc. I've been trying to compare V_z
results from fdelmodc with devito. The results for the non-homogeneous case
with absorbing boundary conditions on all 4 sides are matching well, while
random traces are matching for the homogenous case. But somehow, it doesn't
seem to match at all when the free surface boundary condition is applied.
Would the angle filter in fdelmodc be playing a major role in this?

Thanks,
Rifa

**Comment by JanThorbecke** [comment]
Dear Rita, 

The angle filter is only in use when the rec_type_ud= receiver type is enabled. 

I have not yet compared fdelmodc with devito for a medium with a free-surface. fdelmodc has been compared with other modelling scheme’s (also layer based schemes for 1D media) and the results are always in agreement.

with kind regards, 

Jan
