### ISSUE TITLE
Installation problem-NetCDF

### ISSUE THREAD

**Issue by hxya1** [JanThorbecke/OpenSource#12]
Hi,
After installing the software, I try the ./fdelmodc_plane.scr. Error comes:
file_base defined for NetCDF output, but code not compiled for NetCDF support: recompile with -D_NETCDF.

It seems like I need to recompile the codes. Does anyone know how to modify the makefile?
Thx!

**Comment by JanThorbecke** [comment]
You can solve this error by adding the following around line 182 in utils/makemod.c

182   netcdf=0;
183   if (strstr(file_base, ".nc") != NULL) netcdf=1;

after that recompile makemod (in utils give the command 'make install')

**Comment by JanThorbecke** [comment]
The change is now also pushed to the repository and a git pull will get the updated code.

**Comment by hxya1** [comment]
Thank you so much. It now works perfectly!
