### ISSUE TITLE
Little Bug

### ISSUE THREAD

**Issue by IWantBecomeStronger** [JanThorbecke/OpenSource#13]
Hello,Thorbecke, I find a little bug in Code "fdacrtmc" ,in file "boundaries.c" ,The PML in acoustic scheme has a bug.The location is line 293,code is "for(iz=mod->iePz,ipml=0 ; iz<mod->ieZzb ; iz++) " ,Max lose "ipml++",and it causes a false reflection in the lower right corner of the simulated area.
![image](https://github.com/JanThorbecke/OpenSource/assets/95867968/8ca37e12-ac28-4ace-947e-6b2171a0b80d)

                A Marchenko learner from China,thanks!!!

**Comment by JanThorbecke** [comment]
Thank you very much for reporting this bug ! This helps us to make the code more stable. 

The bug is now fixed in the repository and available.

with kind regards, 

Jan

**Comment by IWantBecomeStronger** [comment]
My pleasure!!!
