### ISSUE TITLE
run figure4.scr error

### ISSUE THREAD

**Issue by Frank2024360** [JanThorbecke/OpenSource#17]
When I make successfully, cd /OpenSource/fdelmodc/FiguresPaper, and sh Figure4.scr, I could not get the right result. It told me:

Segmentation fault (core dumped)
ShotR_T120_S1000_Dt5_F30
SIrand.scr
ShotR_T120_S1000_Dt5_F30_rvz
./SIrand.scr: row 19: ShotR_T120_S1000_Dt5_F30_rvz.su: no that file or catalogue

**Comment by JanThorbecke** [comment]
Did you also run Figure2.scr, that creates the input data of the Figure4.scr?

**Comment by Frank2024360** [comment]
It also wrong when I run Figure2.scr firstly then run Figure4.scr.
I do not think it's that issue because I run successfully before when I use the centos7.6, but now I use the ubuntu22. headache~~~

**Comment by JanThorbecke** [comment]
Do you have a more detailed error message, or do you know which program failed.
Maybe there are some left-over object files from a previous install. You can try a make from scratch and run again. 
cd .../OpenSource
make clean
make install

and then try to run again the programs.

**Comment by JanThorbecke** [comment]
Centos or ubuntu should not matter, as long as GNU compilers are installed and Seismic Unix is installed with XDR off.

**Comment by Frank2024360** [comment]
![error](https://github.com/user-attachments/assets/09fa142f-b5a4-4f99-800f-c865d79e8051)

That's the error screenshot.
I make clean and make but also error. 
The program maybe is fdelmodc module. 

Besides, does the install sequence of SU and OpenSource produce matter? I installed SU before and make the OpenSource recently.

**Comment by JanThorbecke** [comment]
Thank you for sending the error message. 
The error is in the wavelet file used in fdelmodc and can be found in the messages just before the segmentation fault. The wavelet file (file_src= argument) is corrupt, dt is set to 0.0000 and it contains 367715936 samples. You can inspect the wavelet file with surange and sumax to see what header and data the file contains and hopefully find the cause why the wavelet file is corrupted.

**Comment by JanThorbecke** [comment]
The order of installation between SU and OpenSource does not matter.

**Comment by Frank2024360** [comment]
I installed the OpenSource by the steps:

1, install the intel MKL in /opt
2, tar -xvf OpenSource.tgz
3, cd OpenSource, cp Make_include_template  Make_include
4, change ROOT=/home/usr/OpenSouce
5, change MKLROOT=/opt/intel/mkl/,
    MKLLIB=${MKLROOT}/lib
6, make

Could you please help me see whether the steps are correct?

**Comment by JanThorbecke** [comment]
The steps look all correct to me. What kind of compiler did you use in Make_include?

**Comment by Frank2024360** [comment]
GNU compiler

**Comment by Frank2024360** [comment]
![error2](https://github.com/user-attachments/assets/2fdc5178-407a-4604-9613-92385c52d493)

And when I just remove the OpenSource, tar the .tgz file and install again, it gave me that error^-^, really magical~~~

**Comment by JanThorbecke** [comment]
The permission denied indicate that you do not have (unix) permission to write in that directory. You can try to run in another directory or change the permission in the current directory (chmod -R u+rwX .)

**Comment by Frank2024360** [comment]
> Thank you for sending the error message. The error is in the wavelet file used in fdelmodc and can be found in the messages just before the segmentation fault. The wavelet file (file_src= argument) is corrupt, dt is set to 0.0000 and it contains 367715936 samples. You can inspect the wavelet file with surange and sumax to see what header and data the file contains and hopefully find the cause why the wavelet file is corrupted.

I tried to install again. 
This time I confirmed the .tgz file, MKL and make file are OK, but Figure4.scr, fdelmodc module, also create the shot.su file failed. 
It is the same wrong about "Segmentation fault". 
Could you please tell me where can I find the wavelet file?

It will be OK when I run other scripts such as Figure3_nofree.scr. It looks like only involve the src_random modeling in fdelmodc will be wrong.

**Comment by JanThorbecke** [comment]
Unfortunately I can't reproduce the observed error. 

When Figure2.scr is run does it produce the following files with the size mentioned in the first column?

16592 simple_cp.su
16592 simple_ro.su
13760 vel_cp.su
13760 vel_ro.su
    8 srcTimeLengthN=20.bin
  640 src_nwav.su
   48 SrcPositions1000.txt
   16 RcvPositions201.txt
13760 SrcRecPositions.su
  104 shotR_T0.01_S1000_Dt0.01_F30_rvz.su
 6352 simple_sources_cp.eps
 9528 simple_cp.eps
11656 simple_srcpos_cp.eps
 6496 sources.eps

**Comment by JanThorbecke** [comment]
Is the problem solved and Figure4.scr runs successfully?

**Comment by Frank2024360** [comment]
> Is the problem solved and Figure4.scr runs successfully?

Sorry for late reply because of our holiday. 
This issue has been addressed. The point is the intel MKL package and the OpenSource were incompatible. If I use the latest OpenSource package with 2020 intel MKL, there will be wrong. I use the latest OpenSource and 2024 intel MKL package will be OK.
Thanks a lot for your concern!
