### ISSUE TITLE
marchenko_pirr.scr error

### ISSUE THREAD

**Issue by leezw5221** [JanThorbecke/OpenSource#19]
Dear Dr. Jan,

When I follow the steps with the command :

mdd file_A=ID.su file_B=iniF/iniFocii_z1100.su file_out=temp.su mdd=3 verbose=1 causal=3 lsqr_damp=0.0001 lsqr_iter=50

The program did not run successfully, it told:

mdd: mdd.c:305: main: Assertion `cdataout != ((void *)0)' failed.
Aborted (core dumped)

Just shown as:
<img width="850" alt="error" src="https://github.com/user-attachments/assets/f3061c38-8acb-40ec-9774-4ce09b72d45d">

I have already installed BLAS, LAPACK, could you please help me with the problem, thank you so much!

Best wishes,
Lee

**Comment by JanThorbecke** [comment]
Dear Lee, 

The cdataout message is an assertion in the code mdd.c Inspecting the code you will see the following:

299     cdataoutSize = nstationA*nstationB*nfreq*sizeof(complex);
300     cdataout     = (complex *)malloc(cdataoutSize);
301     cA           = (complex *)malloc(nstationA*nfreq*nshotA*sizeof(complex));
302     cB           = (complex *)malloc(nstationB*nfreq*nshotB*sizeof(complex));
303     if (file_dmat!=NULL) oBB = (complex *)malloc(nstationB*nstationB*nfreq*sizeof(complex));
304     else oBB = NULL;
305     assert(cdataout != NULL);

The assertions checks if the array allocated at line 300 has been successul. This not the case and I suspect that the array is too large to fit into the memory of the computer running MDD. The size of the array cdataout is computed in line 299 and maybe the number of stations of file_A or B, or the number of frequencies is too large.

**Comment by leezw5221** [comment]
Thank you for your reply, but I cannot run it successfully even when I cut down the shots array. I will find another device to have a try.

**Comment by leezw5221** [comment]
Thank you for your reply, but I cannot run it successfully even when I cut down the shots array. I will find another device to have a try.

**Comment by JanThorbecke** [comment]
You can try to reduce the amount of memory allocated by reducing the frequencies by setting fmin= and fmax=. 
Do you know how much traces there are in file_A and file_B, then the amount of memory allocated for cdataout=tracesA\*tracesB\*nfreq*8 Bytes.

**Comment by leezw5221** [comment]
Thank you so much for your help, this time I tried to cut down the size of the model,  used less shots and receivers, and reduced the frequencies, it still told the same:

![image](https://github.com/user-attachments/assets/81360992-849b-4907-b4a9-c13b3b7b6d0d)

After reading the code in mdd.c and have a discussion, we then tried to exchange the file_A and file_B,  it ran successfully, 

![image](https://github.com/user-attachments/assets/ce11885c-5c0a-4372-9ad4-efe481579c47)

The input ID.su and iniFocii_z1100.su are shown below:

![image](https://github.com/user-attachments/assets/1aa1ba8d-f948-4fe9-aaee-59b381ce249c)
![image](https://github.com/user-attachments/assets/89e979f4-45c7-4a1b-a141-a6345d2de510)

The output temp.su and F2_0.su:
![image](https://github.com/user-attachments/assets/1151beab-235b-47d7-a8f2-973f4bcf055b)
![image](https://github.com/user-attachments/assets/5b95abf4-2b10-426e-8c16-049fd32b3c4d)

In the next steps, I have to exchange the files in every command include mdd,  or it told error like before.
When ran the command 

       fmute file_shot=temp.su file_mute=F2_0.su file_out=temp1.su above=4 verbose=1 hw=8 shift=-15 smooth=3

it told  
![image](https://github.com/user-attachments/assets/9ee42738-3481-4c5f-b272-055dbd2c7e6a)

The new temp.su is shown as:

![image](https://github.com/user-attachments/assets/323bef0c-5a85-4d77-83ff-62dc0d547991)


I don't know how to deal with this, could you please help me,thanks so much.

Best wishes!

**Comment by JanThorbecke** [comment]
The segmentation fault in fmute could indicate that the file_mute= file contains multiple events and the algorithm can not get the first arrivals in that file. Have you tried to add the parameter returnmask=1 and does that give an output file?

**Comment by JanThorbecke** [comment]
Looking at the picture of F2_0.su, the origin of time is in the middle of the time-trace. By shifting the origin to sample 0 (in time) the fmute script can detect the first arrivals. In that case it is possible to use it for both file_shot= F2_0.su file_mute=F2_0.su

**Comment by leezw5221** [comment]
I have tried to add the parameter returnmask=1, however it cannot give the output, then I tried to use the command 'supaste' to make the files temp.su and F2_0.su with the same head, it told segmentation fault (core dumped).

I then tried to use 'sustrip' to make them with no head, and used ‘suaddhead' with the only keys, ns and dt, so that the origin of time is 0, however it also told segmentation fault (core dumped). This F2_0.su looks like this.
![image](https://github.com/user-attachments/assets/3665fc35-2686-4526-b003-be4b181e08a6)

Then I thought maybe I misunderstood you. So I tried to cut the F2_0.su into half in its time samples, and I switched the tmin and  tmax to make it looks like below
![image](https://github.com/user-attachments/assets/beaa9d2f-541e-443b-b7ca-d04191ccbffa)
However ,it told segmentation fault.

I added the parameter returnmask=1 in each attempt, however I can't get any output file. They just told segmentation fault.
Thank you for your help.
Best wishes!

**Comment by JanThorbecke** [comment]
Have you also tried the suggestion to use file_shot= F2_0.su file_mute=F2_0.su with the switched F2_0 (as shown in your last picture)? 
I do not think that the SU headers are a problem. The irregular events in temp.su might be the cause of the problem. The temp.su does not look good and I think that in the steps that generated temp.su something might not be correct and you can try to fix these steps. What kind of data did you expected to see in temp.su?
In cases with a seg-fault you can also recompile fmute with the debugging flag (-g) added during compilation and linking and attach a debugger (e.g. gdb) to the program.

**Comment by JanThorbecke** [comment]
Could you get some progress on this problem?

**Comment by leezw5221** [comment]
Thank you so much for your attention. Not yet actually.

I have tried the suggestion to use file_shot= F2_0.su file_mute=F2_0.su with the switched F2_0, but it didn't work. Maybe it's wrong for me to exchange the two files at first. 

So I am still trying to find how to deal with this program.I think I should try another device with bigger memory, now I am setting the environment of the new device.  

Best Regards.

**Comment by leezw5221** [comment]
Dear Professor,I have installed the program into new device and it works better now. this time I tried to paste the

**Comment by leezw5221** [comment]
We finally tried to change the head of  the ID.su and the iniFocii_z1100.su from the shot_rp.su. Then everything worked well. Perhaps the amount of memory is the other reason, we set dx=20, reduced the total traces, then it worked well. 

Best regards.

**Comment by JanThorbecke** [comment]
Thank you for your feedback and I’m glad that you have it working !

with kind regards, 

Jan
