### ISSUE TITLE
Intel MKL

### ISSUE THREAD

**Issue by Nightwolf86** [JanThorbecke/OpenSource#4]
Hey Guys!

I am new in GitHub, and also in Linux.  I am gonna use this software in my thesis, and I am trying to run the code, but I have some problems with Intel MKL, saying: 

/usr/bin/ld: cannot find -lmkl_gf_lp64
/usr/bin/ld: cannot find -lmkl_sequential
/usr/bin/ld: cannot find -lmkl_core

If you can help me, I will be appreciated.

Thanx

**Comment by JanThorbecke** [comment]
This message could mean:
-1-  That you do not have installed Intel's MKL library. There are 2 solutions:
  a) Install Intel's MKL library and make sure that environment variable $MKLROOT is set.
  b) Comment out the MKL settings in Make_include, then the MKL library is not used and it will use default FFT's that are slower in performance. All code (expect MDD) will be compiled and work perfectly fine.

-2- Intel's MKL is installed, but MKLROOT is not set. You can define the MKLROOT variable in Make_include . Typical MKLROOT path's are /opt/intel/compilers_and_libraries_2018.3.222/linux/mkl
