### ISSUE TITLE
Mistake cc1fft.c 

### ISSUE THREAD

**Issue by ale00999-lab** [JanThorbecke/OpenSource#5]
Hello Jan!!
I Would like to use Marchenko Migration in Colombia Complex Area, it is about the University Project, I followed the instruction but had the next mistake.    
 My Processor is AMD and OS: Ubuntu18
Thanks Regards

make
make[1]: Entering directory '/home/zignal/OpenSource-master/FFTlib'
mkdir -p /home/zignal/OpenSource-master/lib
mkdir -p /home/zignal/OpenSource-master/include
cp -rp genfft.h /home/zignal/OpenSource-master/include/genfft.h
gcc -c -I/home/zignal/OpenSource-master/include -I. -O3 -ffast-math -fopenmp -DMKL -I/include -I/include/fftw -I/home/zignal/OpenSource-master/zfp/include cc1fft.c

. cc1fft.c:3:10: fatal error: mkl_dfti.h: No such file or directory**

 include "mkl_dfti.h"
compilation terminated.
/Make_include:124: recipe for target '/home/zignal/OpenSource-master/lib/libgenfft.a(cc1fft.o)' failed
make[1]: *** [/home/zignal/OpenSource-master/lib/libgenfft.a(cc1fft.o)] Error 1
make[1]: Leaving directory '/home/zignal/OpenSource-master/FFTlib'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JanThorbecke** [comment]
You have to disable the MKL library in Make_include

**Comment by ale00999-lab** [comment]
Thanks,
running but now I have this message

threadAffinity.c: In function ‘threadAffinity’:
threadAffinity.c:107:5: warning: implicit declaration of function ‘vmess’; did you mean ‘access’? [-Wimplicit-function-declaration]
     vmess("%s thread %d, on %s. (core affinity = %s)", prefix, thread, hnbuf, clbuf);
       access
gcc -c -I/home/zignal/OpenSource-master/include -I. -O3 -ffast-math -fopenmp -I/home/zignal/OpenSource-master/zfp/include getpars.c
gcc  -I/home/zignal/OpenSource-master/include -I. -O3 -ffast-math -fopenmp -I/home/zignal/OpenSource-master/zfp/include -o fdelmodc fdelmodc.o acoustic2.o acoustic4.o acousticSH4.o acoustic4_qr.o acoustic6.o viscoacoustic4.o elastic4.o elastic4dc.o elastic6.o viscoelastic4.o defineSource.o getParameters.o getWaveletInfo.o getModelInfo.o applySource.o applyRupture.o getRecTimes.o getBeamTimes.o writeSnapTimes.o writeRec.o writeSrcRecPos.o decomposition.o fileOpen.o recvPar.o readModel.o sourceOnSurface.o getWaveletHeaders.o boundaries.o verbosepkg.o writesufile.o gaussGen.o spline3.o CMWC4096.o wallclock_time.o name_ext.o atopkge.o docpkge.o threadAffinity.o getpars.o -L/home/zignal/OpenSource-master/lib -lgenfft   -L/home/zignal/OpenSource-master/zfp/lib -lzfp
/usr/bin/ld: cannot find -lzfp
collect2: error: ld returned 1 exit status
Makefile:66: recipe for target 'fdelmodc' failed
make[1]: *** [fdelmodc] Error 1
make[1]: Leaving directory '/home/zignal/OpenSource-master/fdelmodc'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JanThorbecke** [comment]
Is the zfp library installed in the OpenSource directory? Otherwise you can remove -lzfp from the link command. The 3D marchenko programs will not compile without zfp.

All the best,

Jan

**Comment by JanThorbecke** [comment]
There was a mistake in 

zfp/Makefile

you have to change line 47 of zfp/Makefile into:

 install: all

Jan

**Comment by ale00999-lab** [comment]
Thanks Jan.
I made this change    zfp/Makefile   to change line 47 of zfp/Makefile into:  install: all
is running but now I have this message.


threadAffinity.c:107:5: warning: implicit declaration of function ‘vmess’; did you mean ‘access’? [-Wimplicit-function-declaration]
     vmess("%s thread %d, on %s. (core affinity = %s)", prefix, thread, hnbuf, clbuf);
     ^~~~~
     access
gcc -c -I/home/zignal/OpenSource-master/include -I. -O3 -ffast-math -fopenmp -I/home/zignal/OpenSource-master/zfp/include getpars.c
gcc  -I/home/zignal/OpenSource-master/include -I. -O3 -ffast-math -fopenmp -I/home/zignal/OpenSource-master/zfp/include -o fdelmodc fdelmodc.o acoustic2.o acoustic4.o acousticSH4.o acoustic4_qr.o acoustic6.o viscoacoustic4.o elastic4.o elastic4dc.o elastic6.o viscoelastic4.o defineSource.o getParameters.o getWaveletInfo.o getModelInfo.o applySource.o applyRupture.o getRecTimes.o getBeamTimes.o writeSnapTimes.o writeRec.o writeSrcRecPos.o decomposition.o fileOpen.o recvPar.o readModel.o sourceOnSurface.o getWaveletHeaders.o boundaries.o verbosepkg.o writesufile.o gaussGen.o spline3.o CMWC4096.o wallclock_time.o name_ext.o atopkge.o docpkge.o threadAffinity.o getpars.o -L/home/zignal/OpenSource-master/lib -lgenfft   -L/home/zignal/OpenSource-master/zfp/lib -lzfp
defineSource.o: In function `normal':
defineSource.c:(.text+0xa9f): undefined reference to `__exp_finite'
defineSource.o: In function `defineSource':
defineSource.c:(.text+0x2323): undefined reference to `sincos'
defineSource.c:(.text+0x2356): undefined reference to `sin'
getParameters.o: In function `getParameters':
getParameters.c:(.text+0x3359): undefined reference to `sincos'
getParameters.c:(.text+0x374a): undefined reference to `__expf_finite'
getParameters.c:(.text+0x377a): undefined reference to `__expf_finite'
getParameters.c:(.text+0x3818): undefined reference to `__expf_finite'
getParameters.c:(.text+0x3865): undefined reference to `__expf_finite'
getParameters.c:(.text+0x4ea3): undefined reference to `sin'
applySource.o: In function `applySource':
applySource.c:(.text+0xceb): undefined reference to `cos'
applySource.c:(.text+0xdde): undefined reference to `cos'
applySource.c:(.text+0xeab): undefined reference to `cos'
applySource.c:(.text+0x1f32): undefined reference to `sincos'
applySource.c:(.text+0x1f72): undefined reference to `sincos'
applySource.c:(.text+0x1fbd): undefined reference to `sincos'
applySource.c:(.text+0x1fee): undefined reference to `sin'
applySource.c:(.text+0x200d): undefined reference to `sincos'
applySource.c:(.text+0x2147): undefined reference to `sincos'
applySource.c:(.text+0x2185): undefined reference to `sincos'
applySource.c:(.text+0x21d5): undefined reference to `sincos'
applySource.c:(.text+0x220f): undefined reference to `sin'
applySource.c:(.text+0x2231): undefined reference to `sincos'
decomposition.o: In function `decudP':
decomposition.c:(.text+0xad): undefined reference to `sin'
decomposition.c:(.text+0x2a7): undefined reference to `cos'
decomposition.o: In function `decudVz':
decomposition.c:(.text+0x50e): undefined reference to `sin'
decomposition.c:(.text+0x700): undefined reference to `cos'
decomposition.o: In function `kxwdecomp':
decomposition.c:(.text+0xcc0): undefined reference to `sin'
recvPar.o: In function `recvPar':
recvPar.c:(.text+0x28c1): undefined reference to `cos'
recvPar.c:(.text+0x2924): undefined reference to `sin'
recvPar.c:(.text+0x2ab5): undefined reference to `sin'
recvPar.c:(.text+0x2c0f): undefined reference to `sin'
recvPar.c:(.text+0x2c85): undefined reference to `sincos'
boundaries.o: In function `boundariesP':
boundaries.c:(.text+0x2f3): undefined reference to `__log_finite'
boundaries.c:(.text+0x3f1): undefined reference to `__pow_finite'
boundaries.c:(.text+0x1d11c): undefined reference to `__pow_finite'
boundaries.o: In function `boundariesV':
boundaries.c:(.text+0x1e9aa): undefined reference to `__log_finite'
boundaries.c:(.text+0x1ea9b): undefined reference to `__pow_finite'
boundaries.c:(.text+0x1eb18): undefined reference to `__pow_finite'
boundaries.c:(.text+0x1eb9a): undefined reference to `__pow_finite'
boundaries.c:(.text+0x1ed2b): undefined reference to `_ZGVbN2vv___pow_finite'
boundaries.c:(.text+0x1ed56): undefined reference to `_ZGVbN2vv___pow_finite'
boundaries.c:(.text+0x1ee5a): undefined reference to `__pow_finite'
boundaries.c:(.text+0x1eee0): undefined reference to `__pow_finite'
boundaries.c:(.text+0x1ef6a): undefined reference to `__pow_finite'
boundaries.c:(.text+0x1eff4): undefined reference to `__pow_finite'
boundaries.c:(.text+0x1f07e): undefined reference to `__pow_finite'
boundaries.o:boundaries.c:(.text+0x1f10a): more undefined references to `__pow_finite' follow
gaussGen.o: In function `gaussGen':
gaussGen.c:(.text+0x62): undefined reference to `__log_finite'
gaussGen.o: In function `gaussian':
gaussGen.c:(.text+0x11b): undefined reference to `__log_finite'
/home/zignal/OpenSource-master/lib/libgenfft.a(optnumber.o): In function `optncc':
optnumber.c:(.text+0x15): undefined reference to `__log_finite'
optnumber.c:(.text+0x3e): undefined reference to `__pow_finite'
/home/zignal/OpenSource-master/lib/libgenfft.a(optnumber.o): In function `optncr':
optnumber.c:(.text+0x95): undefined reference to `__log_finite'
optnumber.c:(.text+0xbe): undefined reference to `__pow_finite'
/home/zignal/OpenSource-master/lib/libgenfft.a(optnumber.o): In function `loptncr':
optnumber.c:(.text+0x117): undefined reference to `__log_finite'
optnumber.c:(.text+0x142): undefined reference to `__pow_finite'
/home/zignal/OpenSource-master/lib/libgenfft.a(optnumber.o): In function `optnccf':
optnumber.c:(.text+0x1a5): undefined reference to `__log_finite'
optnumber.c:(.text+0x1ce): undefined reference to `__pow_finite'
/home/zignal/OpenSource-master/lib/libgenfft.a(optnumber.o): In function `optncrf':
optnumber.c:(.text+0x225): undefined reference to `__log_finite'
optnumber.c:(.text+0x24e): undefined reference to `__pow_finite'
/home/zignal/OpenSource-master/lib/libgenfft.a(lib_fft.o): In function `cc1_fft':
lib_fft.c:(.text+0x27): undefined reference to `__log_finite'
lib_fft.c:(.text+0x68): undefined reference to `__pow_finite'
/home/zignal/OpenSource-master/lib/libgenfft.a(lib_fft.o): In function `ccm_fft':
lib_fft.c:(.text+0x185): undefined reference to `__log_finite'
lib_fft.c:(.text+0x1c5): undefined reference to `__pow_finite'
/home/zignal/OpenSource-master/lib/libgenfft.a(lib_fft.o): In function `ccdft':
lib_fft.c:(.text+0x48d): undefined reference to `sincosf'
/home/zignal/OpenSource-master/lib/libgenfft.a(lib_fft.o): In function `rcdft':
lib_fft.c:(.text+0x72c): undefined reference to `sincos'
/home/zignal/OpenSource-master/lib/libgenfft.a(lib_fft.o): In function `rc1_fft':
lib_fft.c:(.text+0x9f2): undefined reference to `__log_finite'
lib_fft.c:(.text+0xa33): undefined reference to `__pow_finite'
/home/zignal/OpenSource-master/lib/libgenfft.a(lib_fft.o): In function `rcm_fft':
lib_fft.c:(.text+0xbf8): undefined reference to `__log_finite'
lib_fft.c:(.text+0xc39): undefined reference to `__pow_finite'
/home/zignal/OpenSource-master/lib/libgenfft.a(lib_fft.o): In function `crdft':
lib_fft.c:(.text+0x10a4): undefined reference to `sincos'
/home/zignal/OpenSource-master/lib/libgenfft.a(lib_fft.o): In function `cr1_fft':
lib_fft.c:(.text+0x1462): undefined reference to `__log_finite'
lib_fft.c:(.text+0x14a3): undefined reference to `__pow_finite'
/home/zignal/OpenSource-master/lib/libgenfft.a(lib_fft.o): In function `crm_fft':
lib_fft.c:(.text+0x194a): undefined reference to `__log_finite'
lib_fft.c:(.text+0x198a): undefined reference to `__pow_finite'
/home/zignal/OpenSource-master/lib/libgenfft.a(pfafft.o): In function `pfacr':
pfafft.c:(.text+0x58ca): undefined reference to `sin'
pfafft.c:(.text+0x58fa): undefined reference to `sinf'
/home/zignal/OpenSource-master/lib/libgenfft.a(pfafft.o): In function `pfarc':
pfafft.c:(.text+0x5c61): undefined reference to `sin'
pfafft.c:(.text+0x5c91): undefined reference to `sinf'
/home/zignal/OpenSource-master/lib/libgenfft.a(pfafft.o): In function `pfa2cr':
pfafft.c:(.text+0xb4b7): undefined reference to `sin'
pfafft.c:(.text+0xb4e6): undefined reference to `sinf'
/home/zignal/OpenSource-master/lib/libgenfft.a(pfafft.o): In function `pfa2rc':
pfafft.c:(.text+0xc340): undefined reference to `sin'
pfafft.c:(.text+0xc377): undefined reference to `sinf'
/home/zignal/OpenSource-master/lib/libgenfft.a(kiss_fft.o): In function `kiss_fft_alloc':
kiss_fft.c:(.text+0xac5): undefined reference to `sincos'
kiss_fft.c:(.text+0xc4d): undefined reference to `sincos'
collect2: error: ld returned 1 exit status
Makefile:66: recipe for target 'fdelmodc' failed
make[1]: *** [fdelmodc] Error 1
make[1]: Leaving directory '/home/zignal/OpenSource-master/fdelmodc'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
(base) root@zignal-desktop:/home/zignal/OpenSource-master#

**Comment by JanThorbecke** [comment]
libm is missing by the link line . You can add ‘-lm’ to LIBS in Make_include or in the Makefile the fdelmodc directory.

**Comment by ale00999-lab** [comment]
Thanks a lot Jan.  I had installed software then I will show you results.
