### ISSUE TITLE
Trying to run acoustic SH4

### ISSUE THREAD

**Issue by NithuSeis** [JanThorbecke/OpenSource#7]
Dear Sir,

We are trying to run acousticSH4( ) for SH wave modeling. But the output results shows zero and nan values.
Kindly help in correcting the execution. 
Attached herewith is the snap of input parameters.
![acousticSH4_inputs](https://user-images.githubusercontent.com/83757089/117272499-deab2a00-ae78-11eb-84f2-b605dec52f87.PNG)

**Comment by JanThorbecke** [comment]
Can you sent me the script (as shown in your screenshot) in ascii, then I will try to reproduce the problem on our own system.
