### ISSUE TITLE
Errors in installation

### ISSUE THREAD

**Issue by mirmusz** [JanThorbecke/OpenSource#8]
Dear Sir,

I'm new in using linux. I am trying to install your "opensource" codes following the installation guides given. However, I encountered some error. Hereby I attached the logs that i got after I type the "make" in the "opensource" directory.
[error.txt](https://github.com/JanThorbecke/OpenSource/files/6928352/error.txt)

I have installed the MKL from https://software.intel.com/content/www/us/en/develop/tools/oneapi/base-toolkit/download.html

Am I missing some important steps?

**Comment by JanThorbecke** [comment]
Hello mirmusz, 

The library with math functions is missing. Can you add in your Make_include:

#LIBARIES
LIBS= -L$L -lgenfft $(BLAS) -lm

#ar FLAGS
ARFLAGS = rvU

The 'rvU' should fix the warning with the libraries and the '-lm' includes the math libraries. Can you let me know if this fixes your problem?

all the best, 

Jan

**Comment by mirmusz** [comment]
Dear Sir Jan,

Thank you for the reply. I have added as per instructed. Seems the errors being reduced. Here is the next error I got:
[error2.txt](https://github.com/JanThorbecke/OpenSource/files/6929116/error2.txt)

Here also my make_include file for your references:
[make_include.txt](https://github.com/JanThorbecke/OpenSource/files/6929119/make_include.txt)

I noticed this step in the installation guide
![set](https://user-images.githubusercontent.com/87347555/128133874-a65e9362-00d7-43d4-83f8-ee52be829bd3.JPG)
I did not make any change of it yet. Is it leads to the errors?

Regards,
mirmusz

**Comment by JanThorbecke** [comment]
You are almost there and only the extrap directory has a problem. Can you add in the Make_include

#LIBARIES
LIBS= -L$L -lgenfft $(BLAS)
ifeq ($(FC),ifort)
   LIBS += -lifcore
endif
ifeq ($(FC),gfortran)
   LIBS += -lgfortran
endif

To use the generated executables you have to set the directory in the PATH variable: replace 'path_to_this_directory' with the path where you have the Make_include  (command 'pwd' in unix).

with kind regards,

Jan

**Comment by mirmusz** [comment]
This is the outcomes after I added the lines:
[error3.txt](https://github.com/JanThorbecke/OpenSource/files/6929603/error3.txt)

The make_include looks like this:
![lib](https://user-images.githubusercontent.com/87347555/128144810-488d313f-3053-440f-b620-dd45f119d37b.JPG)

Regards,
mirmusz

**Comment by JanThorbecke** [comment]
As a workaround can you add the following in

extrap/main/Makefile

LIBS += -L$L -lextrap2d -lgenfft $(BLAS) -lgfortran -lm

I will try to fix this in a better way on the GitHub.

**Comment by mirmusz** [comment]
After I added the lines in extrap/main/Makefile, I got this error:
![nofor](https://user-images.githubusercontent.com/87347555/128148022-fc3e907f-2150-46c5-a54e-4a7becbf06a8.JPG)

Then I edit MDD/Makefile, change **-nofor-main** to **-Wno-main** and redo "make".

Here is the final outcomes:
[final.txt](https://github.com/JanThorbecke/OpenSource/files/6929776/final.txt)

Looks like no more errors message. It is completed? :)

**Comment by JanThorbecke** [comment]
Well done all code has compiled succesfully !

**Comment by mirmusz** [comment]
Thank you so much for the great help Sir Jan! Really appreciate it!

**Comment by mirmusz** [comment]
Hello Sir Jan,

I tried to install again using your updated version of the package. I got this error.
![mkl error](https://user-images.githubusercontent.com/87347555/129469044-80f153bc-425a-4a06-8e08-efad8d9f723a.JPG)

**Comment by JanThorbecke** [comment]
The include files of Intel's MKL can not be found. In the Make_include the MKLROOT variable it not set to the correct path where MKL is located. You have to change the current setting MKLROOT=/opt/intel/mkl/ to the path where MKL is located on your machine.

**Comment by mirmusz** [comment]
Dear Sir Jan,

Great! In my machine, I noticed the "include" is located in /opt/intel/oneapi/mkl/2021.3.0
![mkl_loc](https://user-images.githubusercontent.com/87347555/129473154-6aa260a0-8fa2-4744-bcb7-aed7bee9255f.JPG)

Done with the installation.

Thanks.
